[package]
name = "yahtzee"
version = "0.1.0"
authors = ["Dylan Burton <dylanjburton2@gmail.com>"]
edition = "2018"

[[bin]]
name = "yahtzee"
path = "bin/yahtzee.rs"

[dependencies]
rand = "0.7.3"
derive_is_enum_variant = "0.1.1"